#!/usr/bin/env python3
#username:password is base 64 encoded

import requests
import json

url = "https://switch-ip/restconf/data/Cisco-IOS-XE-interfaces-oper:interfaces/interface=GigabitEthernet1%2F0%2F1/"
#Data for interface Gi1/0/1

payload = {}
headers = {
  'Accept': 'application/yang-data+json',
  'Content-Type': 'application/yang-data+json',
  'Authorization': 'Basic username:password='
}

response = requests.request("GET", url, verify=False, headers=headers, data = payload)
#Convert response to python dictionary
rest_api_data = response.json()
output_file = open ("Interface.json", "w")
json.dump(rest_api_data, output_file, indent=1)
output_file.close()
if rest_api_data["Cisco-IOS-XE-interfaces-oper:interface"]["admin-status"] == "if-state-up":
    print ("Interface is up. Output saved to file.")
else:
    print ("Interface is down. Output saved to file.")
