#!/usr/bin/env python3
#username:password is base 64 encoded

import requests
import json

url = "https://ios-xe-switch-ip/restconf/data/Cisco-IOS-XE-native:native"

payload = {}
headers = {
  'Accept': 'application/yang-data+json',
  'Content-Type': 'application/yang-data+json',
  'Authorization': 'Basic username:password'
}

#username:password is Base64 encoding
response = requests.request("GET", url, verify=False, headers=headers, data = payload)
#print(response.text.encode('utf8'))
print(response.text)
